matricula/config/routes.rb
Matricula::Application.routes.draw do
  resources :alumnos

end

matricula/app/models/alumno.rb
class Alumno < ActiveRecord::Base
end

matricula/app/controllers/alumnos_controller.rb
class AlumnosController < ApplicationController
  # GET /alumnos
  # GET /alumnos.json
  def index
    @alumnos = Alumno.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @alumnos }
    end
  end

  # GET /alumnos/1
  # GET /alumnos/1.json
  def show
    @alumno = Alumno.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @alumno }
    end
  end

  # GET /alumnos/new
  # GET /alumnos/new.json
  def new
    @alumno = Alumno.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @alumno }
    end
  end

  # GET /alumnos/1/edit
  def edit
    @alumno = Alumno.find(params[:id])
  end

  # POST /alumnos
  # POST /alumnos.json
  def create
    @alumno = Alumno.new(params[:alumno])

    respond_to do |format|
      if @alumno.save
        format.html { redirect_to @alumno, notice: 'Alumno was successfully created.' }
        format.json { render json: @alumno, status: :created, location: @alumno }
      else
        format.html { render action: "new" }
        format.json { render json: @alumno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /alumnos/1
  # PUT /alumnos/1.json
  def update
    @alumno = Alumno.find(params[:id])

    respond_to do |format|
      if @alumno.update_attributes(params[:alumno])
        format.html { redirect_to @alumno, notice: 'Alumno was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @alumno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alumnos/1
  # DELETE /alumnos/1.json
  def destroy
    @alumno = Alumno.find(params[:id])
    @alumno.destroy

    respond_to do |format|
      format.html { redirect_to alumnos_url }
      format.json { head :no_content }
    end
  end
end

matricula/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

matricula/app/helpers/alumnos_helper.rb
module AlumnosHelper
end

matricula/app/helpers/application_helper.rb
module ApplicationHelper
end

matricula/app/views/alumnos/_form.html.erb
<%= form_for(@alumno) do |f| %>
  <% if @alumno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alumno.errors.count, "error") %> prohibited this alumno from being saved:</h2>

      <ul>
      <% @alumno.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

matricula/app/views/alumnos/edit.html.erb
<h1>Editing alumno</h1>

<%= render 'form' %>

<%= link_to 'Show', @alumno %> |
<%= link_to 'Back', alumnos_path %>

matricula/app/views/alumnos/index.html.erb
<h1>Listing alumnos</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @alumnos.each do |alumno| %>
  <tr>
    <td><%= alumno.name %></td>
    <td><%= link_to 'Show', alumno %></td>
    <td><%= link_to 'Edit', edit_alumno_path(alumno) %></td>
    <td><%= link_to 'Destroy', alumno, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Alumno', new_alumno_path %>

matricula/app/views/alumnos/new.html.erb
<h1>New alumno</h1>

<%= render 'form' %>

<%= link_to 'Back', alumnos_path %>

matricula/app/views/alumnos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @alumno.name %>
</p>


<%= link_to 'Edit', edit_alumno_path(@alumno) %> |
<%= link_to 'Back', alumnos_path %>

matricula/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Matricula</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>